export enum Icons {
  JavaScript = '󰌞 ',
  TypeScript = '󰛦 ',
  Python = '󰌠 ',
  Rust = '󱘗 ',
  Vue = '󰡄 ',
  Shell = ' ',
  Java = '󰬷 ',
  Docker = '󰡨 ',
  SQL = '󰆼 ',
  Lua = '󰢱 ',
  C = ' ',
  Cpp = '󰙲 ',

  Linux = ' ',
  ArchLInux = '󰣇 ',
  Windows = ' ',

  MySQL = ' ',
  PostgreSQL = ' ',
  MongoDB = ' ',
  Redis = ' ',

  AWS = '󰸏 ',
  Git = '󰊢 ',
  GitHub = '󰊤 ',
  GitLab = '󰮠 ',
  Node = '󰎙 ',
  Express = '󰎙 ',
  React = '󰜈 ',
  Spring = ' ',
  OrangePi = '󰐿 ',
  RaspberryPi = ' ',

  NPM = '󰛷 ',
  Yarn = ' ',
  Cargo = '󱘗 ',
  NeoVim = ' ',
  VSCode = '󰨞 ',

  TailwindCSS = '󱏿 ',
}
