export enum Icons {
  JavaScript = 'nf-md-language_javascript',
  TypeScript = 'nf-md-language_typescript',
  Python = 'nf-md-language_python',
  Rust = 'nf-md-language_rust',
  Vue = 'nf-md-vuejs',
  Shell = 'nf-cod-terminal_bash',
  Java = 'nf-md-language_java',
  Docker = 'nf-md-docker',
  SQL = 'nf-md-database',
  Lua = 'nf-md-language_lua',
  C = 'nf-custom-c',
  'C++' = 'nf-custom-cpp',

  Linux = 'nf-cod-terminal_linux',
  ArchLInux = 'nf-linux-archlinux',
  Gentoo = 'nf-linux-gentoo',
  Windows = 'nf-md-microsoft_windows',

  MySQL = 'nf-dev-mysql',
  PostgreSQL = 'nf-dev-postgresql',
  MongoDB = 'nf-dev-mongodb',
  Redis = 'nf-dev-redis',

  AWS = 'nf-md-aws',
  Git = 'nf-md-git',
  GitHub = 'nf-md-github',
  GitLab = 'nf-seti-gitlab',
  Node = 'nf-dev-nodejs_small',
  Express = 'nf-dev-nodejs_small',
  React = 'nf-md-react',
  Spring = 'nf-seti-spring',
  OrangePi = 'nf-md-raspberry_pi',
  RaspberryPi = 'nf-linux-raspberry_pi',

  NPM = 'nf-dev-npm',
  Yarn = 'nf-seti-yarn',
  Cargo = 'nf-md-language_rust',
  NeoVim = 'nf-custom-vim',
  VSCode = 'nf-md-microsoft_visual_studio_code',

  TailwindCSS = 'nf-md-tailwind',
}
